arch: Swinunet
batch_size: 2
best_iou: null
dataset: vessel_224
deep_supervision: false
early_stopping: -1
epochs: 500
factor: 0.1
gamma: 0.6666666666666666
img_ext: .png
init_type: kaiming
input_channels: 3
input_h: 224
input_w: 224
loss: BCEDiceLoss
lr: 0.01
mask_ext: .png
milestones: 1,2
min_lr: 1.0e-08
momentum: 0.9
name: vessel_224_Swinunet_woDS
nesterov: false
num_classes: 1
num_workers: 0
optimizer: SGD
output_channels: 3
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 0
